{% set version = "1.17.0" %}

package:
  name: pyresample
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyresample/pyresample-{{ version }}.tar.gz
  sha256: 6b3d76194bbf2147d279d9bb2f687f1f5a4516813b7025ab2b3f676d11dc573e

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - configobj
    - numpy >=1.10.0
    - pykdtree >=1.3.1
    - pyproj >=1.9.5.1
    - pyyaml
    - setuptools >=3.2
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pyresample
    - pyresample.bilinear
    - pyresample.ewa._ll2cr
    - pyresample.ewa._fornav
    - pyresample.gradient._gradient_search
  requires:
    - pip
    - dask
    - xarray
    - shapely
  commands:
    - pip check

about:
  home: https://github.com/pytroll/pyresample/
  summary: Geospatial image resampling in Python
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
    - djhoese
    - mraspaud
    - pnuu
