{% set version = "1.14.0" %}

package:
  name: pyresample
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyresample/pyresample-{{ version }}.tar.gz
  sha256: 92c418f164957d9d497e314ab1de5cec7bd75744fa391781bb8965bb4fd3142e

build:
  number: 3
  skip: True  # [win and vc<14]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - pyproj >=1.9.5.1,<2.6
    - {{ pin_compatible('numpy') }}
    - configobj
    - pykdtree >=1.3.1
    - pyyaml
    - six

test:
  imports:
    - pyresample
    - pyresample.ewa._ll2cr
    - pyresample.ewa._fornav
    - pyresample.gradient._gradient_search
  requires:
    - dask
    - xarray

about:
  home: https://github.com/pytroll/pyresample/
  license: LGPL-3.0
  license_file: LICENSE.txt
  summary: 'Resampling of remote sensing data in Python'

extra:
  recipe-maintainers:
    - ocefpaf
    - djhoese
    - mraspaud
    - pnuu
