{% set version = "1.12.3" %}

package:
  name: pyresample
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyresample/pyresample-{{ version }}.tar.gz
  sha256: cd16315b5928947d4126f97ce8f2c22c085108207fb216fe6c7d2dda70c15641

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - pyproj >=1.9.5.1
    - {{ pin_compatible('numpy') }}
    - configobj
    - pykdtree >=1.3.1
    - pyyaml
    - six

test:
  imports:
    - pyresample

about:
  home: https://github.com/pytroll/pyresample/
  license: LGPL-3.0
  license_file: LICENSE.txt
  summary: 'Resampling of remote sensing data in Python'

extra:
  recipe-maintainers:
    - ocefpaf
    - djhoese
    - mraspaud
    - pnuu
