{% set version = "1.9.3" %}

package:
  name: pyresample
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyresample/pyresample-{{ version }}.tar.gz
  sha256: fe7dc6b2e4a13c74892b50a0ade1cfcfa0842a4b3df7a72e49cb4c90648a1302

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - numpy 1.11.*
  run:
    - python
    - pyproj >=1.9.5.1
    - numpy >=1.11
    - configobj
    - pykdtree >=1.1.1
    - pyyaml
    - six

test:
  imports:
    - pyresample
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
  home: https://github.com/pytroll/pyresample/
  license: LGPL-3.0
  license_file: LICENSE.txt
  summary: 'Resampling of remote sensing data in Python.'

extra:
  recipe-maintainers:
    - ocefpaf
    - djhoese
