{% set version = "1.29.0" %}

package:
  name: pyresample
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyresample/pyresample-{{ version }}.tar.gz
  sha256: ea04159f022670719d10e9583eb2f8061adbca3fc662c0801fb08784830207c9

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - versioneer-518
  host:
    - python
    - pip
    - numpy
    - cython
    - versioneer-518
  run:
    - donfig
    - platformdirs
    - importlib-metadata
    - python
    - setuptools >=3.2
    - pyproj >=3.0
    - configobj
    - pykdtree >=1.3.1
    - pyyaml
    - shapely
    - numpy >=1.21.0
    - importlib_metadata  # [py<310]

test:
  imports:
    - pyresample
    - pyresample.bilinear
    - pyresample.ewa._ll2cr
    - pyresample.ewa._fornav
    - pyresample.gradient._gradient_search
  requires:
    - pip
    - dask
    - xarray
    - shapely

about:
  home: https://github.com/pytroll/pyresample/
  summary: Geospatial image resampling in Python
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
    - djhoese
    - mraspaud
    - pnuu
