{% set version = "1.26.0" %}

package:
  name: pyresample
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyresample/pyresample-{{ version }}.tar.gz
  sha256: fcc0c92aefdef791d699be87a5faafbda1b314e4c3df1259f373ec5807980098

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - versioneer-518
  host:
    - python
    - pip
    - numpy
    - cython
    - versioneer-518
  run:
    - python
    - configobj
    - numpy >=1.10.0
    - pykdtree >=1.3.1
    - pyproj >=2.3.0
    - pyyaml
    - setuptools >=3.2
    - {{ pin_compatible('numpy') }}
    - importlib_metadata  # [py<310]

test:
  imports:
    - pyresample
    - pyresample.bilinear
    - pyresample.ewa._ll2cr
    - pyresample.ewa._fornav
    - pyresample.gradient._gradient_search
  requires:
    - pip
    - dask
    - xarray
    - shapely

about:
  home: https://github.com/pytroll/pyresample/
  summary: Geospatial image resampling in Python
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
    - djhoese
    - mraspaud
    - pnuu
