{% set name = "pyresample" %}
{% set version = "1.31.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyresample-{{ version }}.tar.gz
  sha256: b9cd365a3d5138c4b515b33ff37e7a851160d465e26468f2ba2b6342efef6a41

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 3

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=2.0.0rc1,<2.3                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - versioneer
  host:
    - python
    - pip
    - setuptools
    - numpy >=2.0.0rc1,<2.3
    - cython >=3
    - versioneer
  run:
    - python
    - configobj
    - donfig
    - importlib-metadata  # [py<310]
    - numpy >=1.21.0
    - platformdirs
    - pykdtree >=1.3.1
    - pyproj >=3.0
    - pyyaml
    - setuptools >=3.2
    - shapely

test:
  imports:
    - pyresample
    - pyresample.bilinear
    - pyresample.ewa._ll2cr
    - pyresample.ewa._fornav
    # requires dask
    - pyresample.gradient._gradient_search
  requires:
    - pip
    - dask
    - xarray
    - shapely
  commands:
    - pip check

about:
  home: https://github.com/pytroll/pyresample/
  summary: Geospatial image resampling in Python
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - ocefpaf
    - djhoese
    - mraspaud
    - pnuu
