appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: lvIseKoGzPI2BYeY91k/TgRG5Cql+W2GoTe5LQ8odR6vckAH5+yR1+msmEgLnh10MrEBAPrZ0OCxAH0jCkEvVwWKnik77xO+tPcE5d7JyQjrV4OTbOkPjkINB/crRwfxQRydurM0BdVQaZpqP8+D9K+niVNoIv4g0CQf54Efeqrp5gib8t+6hSbMNdsKW7boTrk4a8uZHdlroFusv+kbSWaKK+aDEdKxFI0ZzwveBsI7bvs1ZD2g7Surfx/6Q6AOFhkzMp+BpbyHEBAoO9qiTzD0JCC6gr7+OgjWTss+/ALL5C2F+nUU2PmfIK/oP/Jf5y34iFzTSZltMzW46knh7mxPx/8rkuCv91sugR7x9l+6E2dOzJ++3tSCXUhpvKHErx/Arkn58xiJ5/ZLmjDNGOyyQdVPIg0OQrd26R8OsmM+w0FfuFGgNcqpKtEgNlS2HLHDEPaVbGkQja6jXAT2pH4elpZYcXLspStWoHUvM8dAs0k95yWxllZw9JXAAj0cfSIx4XcmSkXkkYngKg8GipUVWCf6IQ8vtfl9ZtJvgy9vPkzjiHLPQLvThs3k64neZ/OimjqqFDngpZ9hAmKyTDUHGTewDsrG1+nJYv+amkinrkh6fLU1kzcko24FpxRO3r7IwwvDPqFgi94XMFG4dTMV+lf4V4NeuUCtFGGEYI8=}
provider:
  win: azure
