travis:
  secure:
    BINSTAR_TOKEN: QJUE7f53w98Skjndi568Tdt5lZu0BIpkGkQBb0h4xHT4iuxFgpQcTzZBKXIm50v7l7kRTtsd3ToPlzQkKmTJfmp/RaJ4iJTs7/5tkLoLLCNO3jnfghRPWbMgYjlProLpAwfPMTZtC8HpLTdvhPGGoCgn2n4g6CuwcqLs8RYZDSJkzkDhpPPtsICvOu5P/uBopp6jjj0APkMdRTdS/OuHRgqUSaj+HwPvQWKDKcQq2aTKdO6Sg91zsyNMGRw5agFnrPRT7tMzIxSGCuFZJ7HazpDvHLEJy1uo55+JXHqUM2jkwG0ByxrzsGE4+y6cJk46TRDSg7qoj6Jlw2BFXwnTdE53jUIJ55fgaDsaAdztLC2VKK4pmSayzpd93KMQG1i9OJBaVSlSLbzsFX04YYcWp4da2OP1IGbmS07b72zJbB71N3k4dsPhj9oPHiOA4B98p5JufNmHCaJYchJoCxBNSUmhW9otO/EOB4t2rTKQJwIl1VxYvOOQhUTdNbqduw8EGSvXwqK9DYpserGW01lXUV1am2OL2+bpAsp0+CC7T3NwlfmaaZ2geisHgIeZwjNorli5z4/Q+F5dGQ2OXLWCmVRleg+/fVKRDZ6hzO8anWkDyk2TU6nmj/mMCEMDAPl60eeIDz6UiwcFZHbtfZeuVp8osZ6qSbqNPnjm6NQywIQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
